"use client";

import { useState } from "react";
import { usePathname } from "next/navigation";
import { type FamilyMember, type FamilyMemberErrors } from "../../../lib/onboarding/family-dependents/types";

type Props = { member: FamilyMember; errors: FamilyMemberErrors; isEditing: boolean; onChange: (changes: Partial<FamilyMember>) => void; onSave: (event: React.FormEvent<HTMLFormElement>) => boolean | Promise<boolean>; onCancel: () => void; };
function fieldClasses(hasError = false) { return `form-field w-full rounded-xl border bg-white px-4 py-3.5 text-sm text-navy-900 placeholder:text-slate-400 ${hasError ? "border-red-300" : "border-slate-200"}`; }
function ErrorMessage({ id, message }: { id: string; message?: string }) { return message ? <p id={id} className="mt-2 text-xs font-medium text-red-600" role="alert">{message}</p> : null; }

export default function FamilyMemberForm({ member, errors, isEditing, onChange, onSave, onCancel }: Props) {
  const isProfile = usePathname() === "/investor/profile"; const [profileOpen, setProfileOpen] = useState(false); const today = new Date().toISOString().slice(0, 10);
  async function handleSubmit(event: React.FormEvent<HTMLFormElement>) { const saved = await onSave(event); if (saved && isProfile) setProfileOpen(false); }
  if (isProfile && !isEditing && !profileOpen) return <div className="flex justify-start"><button type="button" onClick={() => setProfileOpen(true)} className="inline-flex items-center justify-center gap-2 rounded-xl border border-teal-600 bg-white px-5 py-3 text-sm font-bold text-teal-700 shadow-sm transition hover:bg-teal-50">+ Add family member</button></div>;
  return <form noValidate onSubmit={handleSubmit} className="rounded-[28px] border border-teal-200 bg-teal-50/50 p-6 shadow-soft sm:p-8">
    <div className="mb-6 flex items-start justify-between gap-4 border-b border-teal-100 pb-5"><div><p className="text-xs font-bold uppercase tracking-[0.14em] text-teal-700">{isEditing ? "Edit member" : "New member"}</p><h2 className="mt-2 text-xl font-extrabold text-navy-900">Tell us about them</h2></div>{isEditing && <button type="button" onClick={onCancel} className="text-sm font-bold text-slate-500 underline decoration-slate-300 underline-offset-4">Cancel</button>}</div>
    <div className="grid gap-5 sm:grid-cols-2">
      <div><label htmlFor="name" className="mb-2 block text-sm font-semibold text-navy-900">Name</label><input id="name" autoComplete="name" value={member.name} onChange={(e) => onChange({ name: e.target.value })} aria-invalid={Boolean(errors.name)} placeholder="Their full name" className={fieldClasses(Boolean(errors.name))} /><ErrorMessage id="name-error" message={errors.name} /></div>
      <div><label htmlFor="relationship" className="mb-2 block text-sm font-semibold text-navy-900">Relationship</label><input id="relationship" value={member.relationship} onChange={(e) => onChange({ relationship: e.target.value })} aria-invalid={Boolean(errors.relationship)} placeholder="e.g. Child, parent, partner" className={fieldClasses(Boolean(errors.relationship))} /><ErrorMessage id="relationship-error" message={errors.relationship} /></div>
      <div><label htmlFor="dateOfBirth" className="mb-2 block text-sm font-semibold text-navy-900">Date of birth</label><input id="dateOfBirth" type="date" max={today} autoComplete="bday" value={member.dateOfBirth} onChange={(e) => onChange({ dateOfBirth: e.target.value })} aria-invalid={Boolean(errors.dateOfBirth)} className={fieldClasses(Boolean(errors.dateOfBirth))} /><ErrorMessage id="dateOfBirth-error" message={errors.dateOfBirth} /></div>
      <div><label htmlFor="occupation" className="mb-2 block text-sm font-semibold text-navy-900">Occupation <span className="ml-1 font-normal text-slate-400">(optional)</span></label><input id="occupation" value={member.occupation} onChange={(e) => onChange({ occupation: e.target.value })} aria-invalid={Boolean(errors.occupation)} placeholder="e.g. Student, Retired, Engineer" className={fieldClasses(Boolean(errors.occupation))} /><ErrorMessage id="occupation-error" message={errors.occupation} /></div>
    </div>
    <fieldset className="mt-6"><legend className="mb-3 text-sm font-semibold text-navy-900">Financial dependency</legend><div className="grid gap-3 sm:grid-cols-2"><label className={`flex cursor-pointer items-center gap-3 rounded-xl border bg-white px-4 py-3 text-sm font-semibold ${member.financialDependency === true ? "border-teal-500 ring-4 ring-teal-50" : "border-slate-200"}`}><input id="financialDependency" type="radio" name="financialDependency" checked={member.financialDependency === true} onChange={() => onChange({ financialDependency: true })} className="h-4 w-4 accent-teal-600" />Financially dependent</label><label className={`flex cursor-pointer items-center gap-3 rounded-xl border bg-white px-4 py-3 text-sm font-semibold ${member.financialDependency === false ? "border-teal-500 ring-4 ring-teal-50" : "border-slate-200"}`}><input type="radio" name="financialDependency" checked={member.financialDependency === false} onChange={() => onChange({ financialDependency: false })} className="h-4 w-4 accent-teal-600" />Financially independent</label></div><ErrorMessage id="financialDependency-error" message={errors.financialDependency} /></fieldset>
    <div className="mt-6"><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-navy-900"><input id="includeInPlanning" type="checkbox" checked={member.includeInPlanning} onChange={(e) => onChange({ includeInPlanning: e.target.checked })} className="h-4 w-4 rounded accent-teal-600" />Include this family member in financial planning calculations</label></div>
    <div className="mt-7 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end">{isEditing && <button type="button" onClick={onCancel} className="rounded-xl border border-slate-200 bg-white px-5 py-3 text-sm font-bold text-navy-900">Cancel</button>}<button type="submit" className="rounded-xl bg-teal-700 px-5 py-3 text-sm font-bold text-white">{isEditing ? "Save changes" : "Add family member"}</button></div>
  </form>;
}