import { apiRequest } from "./client";

export type ContextualPrompt = { id: string; triggerText: string; question: string; actionText: string; actionHref: string; type: "goal" | "strategy" | "liability" | "investment" | "budget" };
export type DiaryEntry = { id: string; planningUnitId: string; date: string; displayDate: string; title?: string; content: string; tags: string[]; prompts: ContextualPrompt[]; followUpNote?: string; isImportant: boolean; createdAt: string; updatedAt: string };
export type FinancialDecision = { id: string; planningUnitId: string; date: string; displayDate: string; fullDate: string; title: string; summary: string; category: "Strategy" | "Investment" | "Debt" | "Goal" | "Allocation" | "General"; source: string; sourceId?: string; metrics: Record<string, unknown>; notes?: string; createdAt: string; historical: boolean };

export { getPlanningUnitId } from "./client";
function mapEntry(e: any): DiaryEntry { const d = new Date(String(e.date)); return { id: String(e.id), planningUnitId: e.planning_unit_id, date: String(e.date), displayDate: d.toLocaleDateString("en-US", { weekday: "long", year: "numeric", month: "long", day: "numeric" }), title: e.title ?? undefined, content: e.content, tags: e.tags ?? [], prompts: (e.prompts ?? []).map((p: any) => ({ id: p.id, triggerText: p.trigger_text, question: p.question, actionText: p.action_text, actionHref: p.action_href, type: p.type })), followUpNote: e.follow_up_note ?? undefined, isImportant: Boolean(e.is_important), createdAt: e.created_at, updatedAt: e.updated_at }; }
function mapDecision(d: any): FinancialDecision { const date = new Date(String(d.date)); return { id: String(d.id), planningUnitId: d.planning_unit_id, date: String(d.date), displayDate: date.toLocaleDateString("en-US", { month: "short", year: "numeric" }), fullDate: date.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" }), title: d.title, summary: d.summary, category: d.category, source: d.source, sourceId: d.source_id ?? undefined, metrics: d.metrics ?? {}, notes: d.notes ?? undefined, createdAt: d.created_at, historical: d.historical !== false }; }
export async function getDiaryEntries(planningUnitId: string) { const rows = await apiRequest<any[]>(`/api/diary/entries?planning_unit_id=${encodeURIComponent(planningUnitId)}`); return rows.map(mapEntry); }
export async function createDiaryEntry(input: { planningUnitId: string; date: string; title?: string; content: string; tags?: string[]; prompts?: ContextualPrompt[]; followUpNote?: string; isImportant?: boolean }) { const e = await apiRequest<any>("/api/diary/entries", { method: "POST", body: JSON.stringify({ planning_unit_id: input.planningUnitId, date: input.date, title: input.title, content: input.content, tags: input.tags ?? [], prompts: (input.prompts ?? []).map(p => ({ id: p.id, trigger_text: p.triggerText, question: p.question, action_text: p.actionText, action_href: p.actionHref, type: p.type })), follow_up_note: input.followUpNote, is_important: input.isImportant ?? false }) }); return mapEntry(e); }
export async function deleteDiaryEntry(planningUnitId: string, entryId: string) { await apiRequest(`/api/diary/entries/${encodeURIComponent(entryId)}?planning_unit_id=${encodeURIComponent(planningUnitId)}`, { method: "DELETE" }); }
export async function getFinancialDecisions(planningUnitId: string) { const rows = await apiRequest<any[]>(`/api/diary/decisions?planning_unit_id=${encodeURIComponent(planningUnitId)}`); return rows.map(mapDecision); }
export async function getSystemFinancialDecisions(planningUnitId: string) { const rows = await apiRequest<any[]>(`/api/diary/decisions/system?planning_unit_id=${encodeURIComponent(planningUnitId)}`); return rows.map(mapDecision); }
export async function createFinancialDecision(input: { planningUnitId: string; date: string; title: string; summary: string; category: FinancialDecision["category"]; source: string; sourceId?: string; metrics?: Record<string, unknown>; notes?: string }) { const d = await apiRequest<any>("/api/diary/decisions", { method: "POST", body: JSON.stringify({ planning_unit_id: input.planningUnitId, date: input.date, title: input.title, summary: input.summary, category: input.category, source: input.source, source_id: input.sourceId, metrics: input.metrics ?? {}, notes: input.notes }) }); return mapDecision(d); }
