import { formatCurrency, getCriticalGoalCount, getTotalCurrentGoalFunding, getTotalMonthlyGoalContributions } from "../../../lib/onboarding/goals/goals";
import type { Goal } from "../../../lib/onboarding/goals/types";
import GoalCard from "./GoalCard";

type Props = { goals: Goal[]; onEdit: (goal: Goal) => void; onRemove: (id: string) => void };

export default function GoalSummary({ goals, onEdit, onRemove }: Props) {
  const currentFunding = getTotalCurrentGoalFunding(goals);
  const monthlyContributions = getTotalMonthlyGoalContributions(goals);
  const criticalGoals = getCriticalGoalCount(goals);
  if (goals.length === 0) return <div className="rounded-[28px] border border-dashed border-slate-300 bg-white px-6 py-10 text-center sm:px-8"><div className="mx-auto flex h-12 w-12 items-center justify-center rounded-full bg-teal-50 text-teal-700" aria-hidden="true">+</div><h2 className="mt-4 text-lg font-extrabold text-navy-900">No goals added yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Add what you want your money to accomplish. You can continue without adding a goal right now.</p></div>;
  return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-navy-900 bg-navy-900 p-5 text-white"><p className="text-xs font-bold uppercase tracking-[0.14em] text-teal-200">Current goal funding</p><p className="mt-2 text-2xl font-extrabold">{formatCurrency(currentFunding)}</p></div><div className="rounded-2xl border border-teal-200 bg-teal-50 p-5 text-navy-900"><p className="text-xs font-bold uppercase tracking-[0.14em] text-teal-700">Monthly contributions</p><p className="mt-2 text-2xl font-extrabold">{formatCurrency(monthlyContributions)}</p></div></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-2xl border border-slate-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-slate-500">Total goals</p><p className="mt-1 text-lg font-extrabold text-navy-900">{goals.length}</p></div><div className="rounded-2xl border border-red-200 bg-white p-4"><p className="text-xs font-bold uppercase tracking-[0.12em] text-red-700">Critical goals</p><p className="mt-1 text-lg font-extrabold text-navy-900">{criticalGoals}</p></div></div><div className="space-y-3">{goals.map((goal) => <GoalCard key={goal.id} goal={goal} onEdit={() => onEdit(goal)} onRemove={() => onRemove(goal.id)} />)}</div></div>;
}